"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[memory_usage]
symbol = "memory "

[aws]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
format = "[$virtualenv]($style)"

[status]
symbol = "[x](bold red) "

[sudo]
symbol = "sudo "
